name: CI to docker hub
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false

  push:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: true


  diagnostics:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false
    - name: Hello world 
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test echo "hello world"
    - name: Repo diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd;ls -d */
    - name: Repo size
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd; du -ckh -d 1 *
    - name: Parent directory diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd;ls -d ../*/
    - name: Parent directory size
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd; du -ckh -d 1 ../*
    - name: Grandparent directory diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd;ls -d ../../*/
    - name: Grandarent directory size
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd; du -ckh -d 2 ../../*
    - name: Root directory diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd;ls -d /*/
    - name: Root directory size
      run: df -h
