name: Test 10x Genomics
on: push
jobs:
  login:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false
    - name: Run image test
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test echo "hello from universc"
    - name: Call UniverSC test
      uses: addnab/docker-run-action@v1
      with:
        image: tomkellygenetics/universc:test
        run: echo "hello from universc"
    - name: Call UniverSC from image
      timeout-minutes: 25
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test timeout 20m git -C ./universc pull --ff-only origin $(git branch --show-current) && bash /universc/test/run_tests_10x_gh_actions.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
    - name: Call UniverSC from container
      timeout-minutes: 25
      uses: addnab/docker-run-action@v1
      with:
        image: tomkellygenetics/universc:test
        run: timeout 20m git -C ./universc pull --ff-only origin $(git branch --show-current) && bash /universc/test/run_tests_10x_gh_actions.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Status
        run: echo "build complete" 

  test-cellranger:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false 
    - name: clear environment
      run: rm -rf *
    - name: Test Cell Ranger
      timeout-minutes: 25      
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test timeout 20m git -C ./universc pull --ff-only origin $(git branch --show-current) && bash /universc/test/run_tests_cellranger_gh_actions.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

  test-10x-v2:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false
    - name: clear environment
      run: rm -rf *
    - name: Test 10x
      timeout-minutes: 25
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test timeout 20m git -C ./universc pull --ff-only origin $(git branch --show-current) && bash /universc/test/run_tests_10x_v2_gh_actions.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

  test-10x:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false
    - name: clear environment
      run: rm -rf *
    - name: Test 10x
      timeout-minutes: 25
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test timeout 20m git -C ./universc pull --ff-only origin $(git branch --show-current) && bash /universc/test/run_tests_10x_gh_actions.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
